title: Squoop's Homepage
description: The homepage of Squoop.
theme: jekyll-theme-midnight

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag